@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US010 - System Sequence Diagram (SSD)

autonumber

actor Customer as Customer
participant ":System" as System

activate Customer

    Customer -> System : whilst looking at one of the properties, selects the option \n to make an offer

    activate System

    System --> System : Checks if this client already has already\n made an offer for that property

        System --> Customer : asks the client for the ammount of the offer
    deactivate System

loop until the price entered is equal or lower than the base price of the property

    Customer -> System : enters the ammount of the offer

    activate System

    System --> System : Checks if the price is valid

end loop

    System --> System : Checks if there are any offers made by\n other client in the same ammount

opt there is no existing offer made by another client in the same\n ammount
            System --> Customer : gives confirmation
    deactivate System
end

opt there is an exiisting offer made by another client in the same\n ammount
        System --> Customer : informs the client that there is an existing offer for the\n same property in the same ammount which will have\n priority over the client's offer
end

@enduml