 @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US020 - System Sequence Diagram (SSD)

autonumber

actor Customer as Customer
participant ":System" as System

activate Customer

    Customer -> System : asks to read answers to the appointment requests

    activate System

        System --> Customer : shows list of appointments
    deactivate System

    Customer -> System : selects appointment

    activate System

        System --> Customer : shows appointment information (agent's response)
    deactivate System
alt accepts
    Customer -> System : accepts appointment conditions
        activate System
end

alt declines
        Customer -> System : gives specification on the declined appointment
end
            System --> Customer : gives confirmation
        deactivate System




@enduml