@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - USS005

autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a store
    activate System

        System --> Employee : requests data for store
    deactivate System

    Employee -> System : types requested data (designation, email adress, contact)
    activate System

        System --> Employee : asks for address data
    deactivate System

    Employee -> System: types requested address data (street, postal code, door number,floor number)
    activate System

        System --> Employee : requests location data
    deactivate System

    Employee -> System : types requested location data (city, district, state)
    activate System

        System --> Employee : shows store preview and asks for confirmed submition
    deactivate System

    Employee -> System : confirms submition
    activate System

        System --> Employee : registers the store
    deactivate System

        System --> Employee : displays operation success
    deactivate System

@enduml