@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

hide circle
hide methods

title US013 - Domain Model

class Store{
designation
phoneNumber
emailAddress
ID
}

class Agent{
name
phoneNumber
emailAddress
}

class StoreManager{
assignedStore
}

class Employee{
name
emailAddress
phoneNumber
}

class NetworkManager{
name
emailAddress
phoneNumber
}

StoreManager "1" -- "1" Store : manages >"
Store "1" -- "*" Agent : employs >
StoreManager -- Employee : is >
Agent -- Employee : is >
NetworkManager -- Employee : is >
NetworkManager -- "*" Agent : lists >

@enduml