@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam lyne type ortho

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US011

class Property{
area
price
distanceFromTheCityCenter
}

class Employee{
name
phoneNumber
emailAddress
}

class Agent{
}

class Order{
orderNumber
clientEmail
price
}


class Customer{
name
phoneNumber
emailAddress
}

class Announcement{
localDate
property
commissionType
commission
requestType
}

class Property{
area
distanceFromTheCityCentre
price
}

class Residence{
numberOfBedrooms
numberOfBathrooms
numberOfParkingSpaces
availableEquipment
}

class House{
existenceOfABasement
inhabitableLoft
}

class SunExposure{
direction
}

class PropertyType{
propertyType
}

class PassportCardNumber{
passportCardNumber
}

class District{
districtName
}

class State{
state
}

class City{
cityName
}

class Address{
doorNumber
floorNumber
street
postalCode
}

class TaxNumber{
taxNumber
}

class PassportCardNumber{
passportCardNumber
}

Announcement "1" -- "1" Property : announces >
Order "*" -- "1" Announcement : > on
Agent "1" --"*" Order : analyzes >
Agent --|> Employee : is a
Residence ---|> Property : is a
House --|> Residence : is a
House -- SunExposure : has >
Customer -- "1" TaxNumber : has >
Customer -- "1" PassportCardNumber : has >
Employee --- "1" TaxNumber : has >
Employee -- "1" PassportCardNumber : has >
Property -- Address : has >
Address -- City : has >
City -- District : is in >
District -- State : is in >
Customer -- Address : has >
Property -- "1" PropertyType : has >
Customer --- "*" Order : makes >


@enduml