@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto

skinparam classAttributeIconSize 0

left to right direction

class RegisterAnnouncementUI

class RegisterAnnouncementController
{
    +getPropertyType()
    +setPropertyType(propertyType)
    +getRegisteredUsers()
    +saveDataProperty(area, location, distance, price, photos)
    +saveDataResidence(bedrooms, bathrooms, parking, equipment
    +saveDataHouse(basement, loft, sun)
    +saveDataComissionType(comissionType)
    +saveDataComission(comission)
}

class Repositories
{
    +getInstance()
    +getPropertyTypeRepository()
    +getRegisteredUsersRepository()
}

class PropertyTypeRepository
{
    +getPropertyType()
}

class RegistedUsersRepository
{
    +getRegisteredUsers()
}

class Announcement
{
    +createAnnouncement()
    +setDate(date)
}

class Comission
{
    -value: double
    -percentage : double
}

class Agent
{
    -name: String
    -citizenCardNumber: Integer
    -taxNumber: Integer
    -adress: String
    -email: String
    -phoneNumber: Integer
    -agency: String
}

Class Location
{
    -street: String
    -city: String
    -district: String
    -state: String
    -zipCode: Integer
}



RegisterAnnouncementUI -> RegisterAnnouncementController
RegisterAnnouncementController .> Repositories
Repositories -> Announcement
Repositories -> RegistedUsersRepository
Repositories -> PropertyTypeRepository
RegisterAnnouncementController ---> Announcement
RegisterAnnouncementController ..> RegistedUsersRepository
RegisterAnnouncementController ..> PropertyTypeRepository
Agent -> Announcement
Announcement -> Comission
Announcement -> "has" Location
@enduml