@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":RegisterStoreUI" as UI
participant ":RegisterStoreController" as STRCTRL
participant ":StateController" as STCTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "StoreRepository:\nStoreRepository" as StoreRepository
participant "StateRepository:\nStateRepository" as StateRepository
participant "DistrictRepository:\nDistrictRepository" as DistrictRepository
participant "CityRepository:\nCityRepository" as CityRepository
participant "Location:\nLocation" as Location
'participant ":ApplicationSession" as _APP
'participant "appSession\n:ApplicationSession" as APP
'participant "currentSession\n:UserSession" as SESSAO
'participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
'participant "organization\n:Organization" as ORG
participant "store\n:Store" as Store

activate ADM

        ADM -> UI : asks to register a store

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> STRCTRL** : create

            UI -> STRCTRL : getRepositories()
            activate STRCTRL

                    STRCTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                    RepositorySingleton --> STRCTRL: repositories
                    deactivate RepositorySingleton

                    STRCTRL -> StoreRepository : getStoreRepository()
                    activate StoreRepository

                    StoreRepository --> STRCTRL : stores
                    deactivate StoreRepository

                    STRCTRL -> StateRepository : getStateRepository()
                    activate StateRepository

                    StateRepository --> STRCTRL : states
                    deactivate StateRepository

            STRCTRL --> UI : States
            deactivate STRCTRL

            UI --> ADM : shows list of states and asks to select one
            deactivate UI

            ADM -> UI : selects a state
            activate UI

            UI -> STRCTRL : getDistrict()
            activate STRCTRL

                    STRCTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                    RepositorySingleton --> STRCTRL: repositories
                    deactivate RepositorySingleton

                    STRCTRL -> StoreRepository : getStoreRepository()
                    activate StoreRepository

                    StoreRepository --> STRCTRL : stores
                    deactivate StoreRepository

                    STRCTRL -> DistrictRepository : getDistrictRepository
                    activate DistrictRepository

                    DistrictRepository --> STRCTRL : districts
                    deactivate DistrictRepository


            STRCTRL --> UI : districts
            deactivate STRCTRL

            UI --> ADM : shows list of districts within the selected state and asks to select one
            deactivate UI

            ADM -> UI : selects a district
            activate UI

            UI --> STRCTRL : getCity()
            activate STRCTRL

                STRCTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                RepositorySingleton --> STRCTRL: repositories
                deactivate RepositorySingleton

                STRCTRL -> StoreRepository : getStoreRepository()
                activate StoreRepository

                StoreRepository --> STRCTRL : stores
                deactivate StoreRepository

                STRCTRL -> CityRepository : getCityRepository
                activate CityRepository

                CityRepository --> STRCTRL : cities
                deactivate CityRepository

            STRCTRL --> UI : cities
            deactivate STRCTRL

            UI --> ADM : show list of cities within the selected district and asks to select one
            deactivate UI

            ADM -> UI: selects a city

            UI --> ADM : requests store location data (streetAdress, zip-code)
            deactivate UI

            ADM -> UI : types requested data
            activate UI

            UI --> ADM : shows selected state, district, city and store location data and asks to confirm
            deactivate UI

            ADM -> UI : submits data
            activate UI

                    UI -> STRCTRL :createStoreLocation(streetAddress, city, district, state, zipCode)
                    activate STRCTRL

                    STRCTRL -> Location : location(streetAddress, city, district, state, zipCode)
                    activate Location

                    Location --> STRCTRL : location object
                    deactivate Location

                    STRCTRL -> UI : location
                    deactivate STRCTRL

            UI --> ADM : requests store data (ID, designation, emailAddress, phoneNumber)
            deactivate UI

            ADM -> UI : types requested data(ID, designation, emailAddress, phoneNumber)
            activate UI

                                UI -> STRCTRL :createStore(ID, designation, emailAddress, phoneNumber)
                                activate STRCTRL

                                STRCTRL -> StoreRepository : createStore(ID, designation, emailAddress, phoneNumber)
                                activate StoreRepository

                                StoreRepository --> STRCTRL : store
                                deactivate StoreRepository

                                STRCTRL -> UI : store
                                deactivate STRCTRL


            UI --> ADM : shows store data and asks to confirm
            deactivate UI

            ADM -> UI : submits data
            activate UI

                UI -> STRCTRL : registerLocationAtStore(store, location)
                activate STRCTRL

                STRCTRL -> StoreRepository : setLocation(location)
                activate StoreRepository

                StoreRepository --> STRCTRL : boolean
                deactivate StoreRepository

                STRCTRL --> UI : boolean
                deactivate STRCTRL

                UI --> ADM : shows store data and asks to confirm
                deactivate UI

                ADM -> UI : submits data
                activate UI

                UI -> STRCTRL : registerStore(store)
                activate STRCTRL


                STRCTRL -> StoreRepository : registerStore(store)
                activate StoreRepository

                StoreRepository --> STRCTRL : boolean
                deactivate StoreRepository

                STRCTRL --> UI : boolean
                deactivate STRCTRL

                UI --> ADM : displays operation success
                deactivate UI

           deactivate UI

deactivate ADM

@enduml