@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Announcement{
property
date
comissionType
comission
requestType
agent
price
owner
store
}

class Request{
requestType
price
agent
owner
store
requestDate
property
startDate
enDate
}

class Property{
address
area
distanceFromCityCenter
propertyType
photographsList
}

class Residence{
numberOfBedrooms
numberOfBathrooms
numberOfParkingSpacings
airConditioning
centralHeating
finalPrice
businessDate
}

class House{
numberOfBedrooms
numberOfBathrooms
numberOfParkingSpacings
airConditioning
centralHeating
finalPrice
businessDate
existenceOfABasement
sunExposure
inhabitableLoft
}

class Legacy_System_Files {
}


System_Administrator --> Legacy_System_Files
Legacy_System_Files "1" --> "0..*" Announcement : contains

Property --|> Residence : contains
Residence --|> House : extends
Request --> Property : contains
Announcement --> Request : contains


@enduml