@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Sell Property

autonumber

actor "Owner" as Owner
participant ":System" as System

activate Owner

    Owner -> System : asks to sell or rent his property
    activate System

        System --> Owner : shows a list of options (sell or rent the property) and asks to select one
    deactivate System

    Owner -> System : selects the sell option
    activate System

        System --> Owner : shows agency list and asks to select one
    deactivate System

    Owner -> System : selects an agency
    activate System

        System --> Owner : shows agents list and asks to select one
    deactivate System

    Owner -> System : selects an agent
    activate System

        System --> Owner : asks to select the type of property (house, apartment or land)
    deactivate System
    Owner -> System : selects the type of property
        activate System

        System --> Owner : requests data

    deactivate System
    Owner -> System : inserts data (area (m2), location, distance from the city centre, \nsome photographs and price)
    alt Property is Apartament or House

        System --> Owner : requests data
    deactivate System

        Owner -> System : inserts data (number of number of bedrooms, number of bathrooms, \nnumber of parking spaces and available equipement)
        activate System

        alt Property is a House

            System --> Owner : requests data
        deactivate System

        Owner -> System : inserts data (existence of a basement and/or inhabitable loft and sun exposure)
        activate System

          end

    end

        System --> Owner : shows requested data and selected property movement
    deactivate System

    Owner -> System : submits data
    activate System

         System --> Owner : shows operation sucess
    deactivate System

@enduml