@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class SendEmailMessage {
}

class Agent {
    name
    phoneNumber
    emailAddress
    taxNumber
    passportCardNumber
    address
    role
    agency
    store
    pass
}


class Address {
     streetAddress
     doorNumber
     floorNumber
     zipCode
     state
     district
     city
}

class Client {
      name
      phoneNumber
      emailAddress
      taxNumber
      passportCardNumber
}

class Property {
       area
       distanceFromTheCityCenter
       address
       propertyType
       photographsList
       finalPrice
       businessDate
}

class Message {
    client
    phone
    announcement
    newVisitStartTime
    newVisitEndTime
}


Agent -- Client: Informs >
(Agent, Client) -- SendEmailMessage: making use of

Property "1" -- "*" Message: has >
SendEmailMessage "1" -- "1" Message: about >
Agent "1" -- Message: decides >
Message "*" -- "1" Client: makes <
Address "1" -- "1" Property: has >

@enduml