@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class EmailResponse {
    emailTo
    emailFrom
    emailSubject
    emailBody
}

class Agent {
    name
    phoneNumber
    emailAddress
    taxNumber
    passportCardNumber
}


'class Address {
'      streetAddress
'      city
'      district
'      state
'      ZipCode
'}

class Client {
      name
      phoneNumber
      emailAddress
      taxNumber
      passportCardNumber
}

class Property {
       type of property
       area
       distance from center
       price
       photos
       state
       propertyCode

}

class BookingRequest {
    visitDate

}

class Address {
      streetAddress
      city
      district
      state
      ZipCode
}

Agent -- Client: Informs >
(Agent, Client) -- EmailResponse: making use of

Property "1" -- "*" BookingRequest: has >
EmailResponse "1" -- "1" BookingRequest: about >
Agent "1" -- BookingRequest: decides >
BookingRequest "*" -- "1" Client: makes <
Address "1" -- "1" Property: has >

@enduml