@startuml
'https://plantuml.com/sequence-diagram

@startuml

class ScheduleVisitUI{
}
class ScheduleVisitController{
-Repositories repositories

+getAnnouncement()
+getInstance()
+checkMinutes()
+checkHour()
+checkYear()
+checkMonth()
+checkDay()
+checkIfValidVisit()
+addMessage()
}

class Repositories{
+Repositories()
+getAuthenticationRepository()
+getInstance()
+getMessageRepository()
+getAnnouncementsRepository()
}



class Message{
-Client loggedInClient
-String phone
-Annoucement announcement
-LocalDateTime newVisitStartTime
-LocalDateTime newVisitEndTime

+checkIfValidVisit()
}

class MessageRepository{
-List<Message> MessageList
-List<Message> MessageCompleteList

+addMessage()
+addComplete()
}

class AuthenticationRepository{
+getCurrentUserSession()
}

class Property{
-PropertyType propertyType
}
class House{
}
class Apartment{
}
class Land{
}

class Annoucement{
Price
Type
Commission
Agent
}

class AnnoucementRepository{
+getAnnouncement()
}



ScheduleVisitUI --> ScheduleVisitController

ScheduleVisitController --> Repositories

Repositories ----> MessageRepository
Repositories ---> AnnoucementRepository
Repositories ---> AuthenticationRepository

Message ->MessageRepository



Annoucement -> AnnoucementRepository
Property -> Annoucement
Property --> House
Property --> Apartment
Property --> Land

@enduml