@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to register a new announcement

    activate System

        System --> Agent : requests type of property

    deactivate System

    Agent -> System : selects one of the types given (apartment, house or land)

    activate System

        System --> Agent : requests data

    deactivate System

    Agent -> System : types the requested data (area in m2, location, distance from the city centre, requested price, comission on the sale, one or more photos)

    opt property is an Apartment/House

        activate System

        System --> Agent : requests data

        deactivate System

        Agent -> System : types the requested data (number of bedrooms and bathrooms, parking spaces, available equipment)

        opt property is a House

            activate System

            System --> Agent : requests data

            deactivate System

            Agent -> System : types the requested data (existence of a basement and inhabitable loft, sun exposure)

            activate System

        end opt

    end opt

        System --> Agent : presents all the data inserted

    deactivate System

    Agent -> System : confirms inserted data

    activate System

        System --> Agent : analyses the data and, if approved, sends a confirmation request before posting

    deactivate System

    Agent -> System : confirms publishment

deactivate Agent

@enduml