@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to register a new announcement

    activate System

        System --> Agent : requests owner email

    deactivate System

    Agent -> System : types owner email

    activate System

    alt owner not registed

    System --> Agent : owner not registed

    end alt

    alt owner registed

        System --> Agent : requests type of property

    deactivate System

    Agent -> System : selects one of the types given (apartment, house or land)

    activate System

        System --> Agent : requests data

    deactivate System

    Agent -> System : types the requested data (area in m2, street adress, city, state, floor number, door number, distance from city center, price)

    activate System

    System --> Agent : requests number of photos

    deactivate System

    Agent -> System : inserts number of photos

    loop while i < numberOfPhotos

    activate System

    System --> Agent : requests photo uri

    deactivate System

    Agent -> System : inserts photo uri

    end loop

    opt property is an Apartment/House

        activate System

        System --> Agent : requests data

        deactivate System

        Agent -> System : types the requested data (number of bedrooms and bathrooms, parking spaces)

        loop while !(availableEquipment == 0)

        activate System

                System --> Agent : requests available equipment

        deactivate System

        Agent -> System : types available equipment

        end loop

        opt property is a House

            activate System

            System --> Agent : requests data

            deactivate System

            Agent -> System : types the requested data (existence of a basement and inhabitable loft, sun exposure)

            activate System

        end opt

    end opt

            System --> Agent : requests data

            deactivate System

            Agent -> System : types comission type and comission

            activate System

        System --> Agent : presents all the data inserted

    deactivate System

    Agent -> System : confirms inserted data

    activate System

        System --> Agent : publishes announcement and sends sms notification to the owner

    deactivate System
end alt
deactivate Agent


@enduml