@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 007

autonumber

actor "Unregistered user" as unregisteredUser
participant ":System" as System
activate unregisteredUser

    unregisteredUser -> System : asks to register in the system
    activate System

        System --> unregisteredUser : requests data (name, passport card number, tax number, \naddress, email address, telephone number and password)
    deactivate System

    unregisteredUser -> System : inserts data
    activate System
    alt valid operation

    System --> unregisteredUser : shows operation success
    deactivate System

    else invalid operation

    loop while the inserted data is wrong

    System --> unregisteredUser : asks to reinsert the invalid data
    activate System

    unregisteredUser -> System : reinserts the data that the system asked for
    deactivate System

    end

    end

    deactivate System

@enduml