@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US004

class Owner{
name
citizenCardNumber
taxNumber
email
phoneNumber
}

class Address{
doorNumber
street
floorNumber
city
state
postalCode
}

class CompanyBranch{
location
email
phoneNumber
}

class Company{
designation
}

class Agent{
name
citizenCardNumber
taxNumber
email
phoneNumber
}

class InitialData{
propertiesNumber
propertyType
saleOrRent
}

class PropertyType{
land
house
apartment
}

class Rent{
pricePerMonth
contractDuration
}

class Sale{
price
}

class PropertyRequest{
location
area
distanceFromCityCenter
photographs
}

class Residence{
numberOfBedrooms
numberOfBathrooms
numberOfParkingSpaces
availableEquipment
}

class House{
basement
loft
sunExposure
}

class Appartment{
}

class Announcement{
}

CompanyBranch "0...*" -- "1" Company : is owned >
CompanyBranch "1    " -- "0...*" Agent : employs >
CompanyBranch "1 " -- "0...*" Address : has an >

Agent "1" -- "                                  0...*" Announcement : reviews and publishes >
Agent "1" -- "1  " Address : has an >
Agent "1" --- "1" PropertyRequest : creates >

Owner "1" -- "0...*" InitialData : specify >
Owner "1" -- "1" PropertyRequest : creates >

InitialData "1  " -- "1" PropertyType : includes >
InitialData "1" -- "      1" Announcement : is included in >

PropertyType <-- Residence

Residence <-- House
Residence <-- Apartment

Announcement --> Sale : can announce >
Announcement --> Rent : can announce >

@enduml