@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US007

class Address{
doorNumber
floorNumber
zipCode
streetAddress
}

class State{
stateName
}

class District{
districtName
}

class City{
cityName
}

class UnregisteredUser{
name
emailAddress
telephoneNumber
password
}

class User{
name
emailAddress
telephoneNumber
}

class PassportCardNumber{
passportCardNumber
}

class TaxNumber{
taxNumber
}

Address --|> State
Address --|> City
Address --|> District
UnregisteredUser --- User : after registration becomes >
UnregisteredUser -- Address : has
User -- Address : has
UnregisteredUser --- TaxNumber : has
UnregisteredUser -- PassportCardNumber : has
User -- TaxNumber : has
User -- PassportCardNumber : has

@enduml