@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US007

class UnregisteredUser{
name
passportNumber
}

class Address{
doorNumber
floorNumber
street
city
state
district
postalCode
}

class TaxNumber{
taxNumber
}

class Role{
roleType
}

UnregisteredUser "1" -- "1" Address : has >
UnregisteredUser "1" -- "1" TaxNumber : has >
UnregisteredUser "1" -- "1" Role : defines >

@enduml