@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Project - Domain Model

class District {
}


class Branch {
    designation
    location
    localManager
}

class Agent {
    name
    citizenCardNumber
    tax number
    address
    email
    phoneNumber
    agency
}

class Property {
    area
    location
    distanceFromCityCentre
    requestedPrice
    typeOfProperty
    photographs
}

class Advertisement {
    date
}

class Residence {
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}

class House {
    basement
    inhabitableLoft
    sunExposure
}

class Comission {
    fixed
    percentage
}

class SystemAdministrator{
  name
  email
  citizenCardNumber
  taxNumber
  physycalAddress
  phoneNumber
}


class Employee {
    name
    citizenCardNumber
    address
    email
    phoneNumber
    taxNumber
    agency
}

class CompanyBranch{
id
name
location
phoneNumber
email
}

class Role{
}


class Store {
    storeName
    phoneNumber
    emailAddress
}

class Address {
    street
    postalCode
    doorNumber
    floorNumber
    city
    state
}
class Owner{
name
citizenCardNumber
taxNumber
email
phoneNumber
}

class Apartment{
}

class Company{
designation
}

class InitialData{
propertiesNumber
propertyType
saleOrRent
}

class PropertyType{
land
house
apartment
}

class Rent{
pricePerMonth
contractDuration
}

class Sale{
price
}

CompanyBranch "0...*" -- "1" Company : is owned >
CompanyBranch "1    " -- "0...*" Agent : employs >
CompanyBranch "1 " -- "0...*" Address : has an >

SystemAdministrator "1" -- "0..*" Store : registers >
SystemAdministrator "1"--"0...*" Employee: registed by <
SystemAdministrator "1"--"1" Employee: is >

Store "1" -- "1" Address : has an >
Store "1"-- "*" Advertisement : displays >

Employee "1"--"1" CompanyBranch: works for >
Employee "0...*"--"1...*" Role: has >

Agent "1" -- "1  " Address : has an >
Agent "1" -- "*" Advertisement : reviews and publishes >
Agent "1" - "1" Comission : defines >

Owner "1" -- "0...*" InitialData : specify >
Owner "1" -- "1" Property : creates request for >
Owner "1" -- "1" Property : owns >
Owner "1" -- "1" Agent: talks to >

InitialData "1  " -- "1" PropertyType : includes >
InitialData "1" -- "      1" Advertisement : is included in >

PropertyType <-- Residence

Residence <-- Appartment

Advertisement --> Sale : can announce >
Advertisement --> Rent : can announce >
Advertisement "1" -- "1" Comission : has >
Advertisement "1" - "1" Property : has >

Branch "1" -- "*" Agent : has >

Property "1" -- "1" Residence : can be >

Residence "1" - "1" House : can be >

Address "1" -- "1" District : is in >






@enduml