@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title US004 - Domain Model

abstract class Property {
    area
    localization
    distanceFromTheCityCentre
    price
    photographs
}

class Owner {
    name
    citizenCardNumber
    taxNumber
    address
    emailAddress
    telephoneNumber
}

class Land{

}

class House{
    bedroomsNumber
    bathroomsNumber
    parkingSpacesNumber
    availableEquipment
    sunExposure
}

class Apartment{
    bedroomsNumber
    bathroomsNumber
    parkingSpacesNumber
    availableEquipment
}
class Agent{
    name
    agencyName
}
class Store {
    storeName
    phoneNumber
    emailAddress
}
class SystemAdministrator {
      name
      email
      citizenCardNumber
      taxNumber
      physycalAdress
      phoneNumber
    }

class Role{
roleType

}
class Address {
    street
    postalCode
    doorNumber
    floorNumber
    city
    state
}
class Employee {
    name
    citizenCardNumber
    adress
    email
    Phonenumber
    taxNumber

}
class User {
    name
    email
    password
}

class Application {

}
class CompanyBranch{
id
name
location
phoneNumber
email
}

Property "1" --|> "1" Owner : has an >
Property "1" --|> "1" Agent : has an >

Property "1" -R-|> "0" Apartment : can be >
Property "1" -R-|> "0" House : can be >
Property "1" -R-----> "0" Land : can be >

SystemAdministrator "1" -- "0..*" Store : registers >
Store "1" -- "0...*" Address : has an >

SystemAdministrator "1"--"0...*" Employee: registed by <

User - Application: requests to \nshow properties >

SystemAdministrator "1" -- "1" Role : has >

Employee "1" -- "1" Role : has >

Agent  --|>  Employee
SystemAdministrator "1"--"1" Employee: is >
Employee "1"--"1" CompanyBranch: manages >
Employee "1"--"1" CompanyBranch: works for >






@enduml