@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto

skinparam classAttributeIconSize 0

left to right direction

class PublishRequestUI

class PublishRequestController
{
    -comissionType: String
    -comission: Double
    -request: Request
    -announcement: Announcement
    -justification: String
    -property: Property
    -date: LocalDate
    -requestType: RequestType
    -agent: Agent
    -price: Double
    -owner: Owner
    -store: Store
    +getRequestsList(agent)
    +getRequestInfo(request)
    +saveDataComissionType(comissionType)
    +saveDataComission(comission)
    +addAnnouncement(announcement)
    +createEmail(announcement, request)
    +excludeRequest(request)
    +getProperty(request)
    +setDate()
    +getRequestType(request)
    +getAgent(request)
    +getOwner(request)
    +getPrice(request)
    +getStore(request)
    +acceptRequest(request)
    +createEmail(request, justification)
    +createAnnouncement(property, date, commissionType, commission, requestType, agent, price, owner, store)
}

class Repositories
{
    +getInstance()
    +getRequestsRepository()
    +getAnnouncementRepository()
}

class RequestRepository
{
    -agent
    -request
    +getRequests(agent)
    +acceptRequest(request)
    +excludeRequest(request)
}

class AnnouncementRepository
{
    -announcement
    +addAnnouncement(announcement)

}

class Announcement
{
    -date: LocalDate
    -property: Property
    -comissionType: String
    -comission: Double
    -requestType: RequestType
}


Class Request
{
     -Property: property
     -price: Double
     -requestType: RequestType
     -agent: Agent
     -store: Store
     -owner: Owner
}

PublishRequestUI -> PublishRequestController
PublishRequestController -> Repositories
Repositories -> AnnouncementRepository
Repositories -> RequestRepository
AnnouncementRepository -> "has" Announcement
RequestRepository --> "has" Request
PublishRequestController --> "creates "Announcement
PublishRequestController ..> AnnouncementRepository
PublishRequestController .> RequestRepository
PublishRequestController --> Request


@enduml