@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class SystemAdministrator {
    name
    phoneNumber
    emailAddress
}

class State {
    stateName
}

class District{
    districtName
}

class City{
    cityName
}

SystemAdministrator "1" -- "1" State : adds >
SystemAdministrator "1" -- "1" District : adds >
SystemAdministrator "1" -- "1" City : adds >

District "1" -- "1" State : is in >

City "1" -- "1" District : is in >

@enduml