@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Store {
    storeName
    phoneNumber
    emailAddress
}

class Address {
    street
    postalCode
    doorNumber
    floorNumber
}

class State {
}

class District {
}

class City {
}


Store "1" -- "1" Address : has an >

@enduml

