@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CreateUserUI{
}

class CreateUserController{
+createUser(name, passportCardNumber, taxNumber, address, emailAddress, phoneNumber, password)
}

class Repositories{
+Repositories()
+getInstance()
+getUserRepository()
}

class UserRepository{
+ List <user> user
+ createUser(name, passportCardNumber, taxNumber, address, emailAddress, phoneNumber, password)
+addUser()
+checkIfUserAlreadyExists
+validateUser()
}

class User{
- String name
- String emailAddress
- int phoneNumber
- String password
+createUser(name, passportCardNumber, taxNumber, address, emailAddress, phoneNumber, password)
}

class PassportCardNumber{
-int passportCardNumber
}

class TaxNumber{
-int taxNumber
}

class Address{
-int doorNumber
-int floorNumber
-String zipCode
-String streetAddress
}

class State{
-String stateName
}

class District{
-String districtName
}

class City{
-String cityName
}

CreateUserUI .-> CreateUserController

CreateUserController ..> Repositories

Repositories --> UserRepository

Repositories --> Repositories : instance
UserRepository --> User

User ---> Address

Address ---|> State
Address --|> City
Address --|> District
User --|> TaxNumber : has
User --|> PassportCardNumber : has
@enduml