@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administrator" as Employee
participant ":System" as System

    Employee -> System : ask to register a new employee.
    activate System

        System --> Employee : show a list of the role of the employee (agente, \nstore manager, store network, manager).

    deactivate System

    Employee -> System : select the role of the employee.
    activate System

    System --> Employee : show a list of agencies.
       deactivate System

        Employee -> System : select the agency.
        activate System

        System --> Employee : request information about employee (name, \ncitizen´s card number, tax number, address, \nemail , phone number and agency).
    deactivate System

    Employee -> System : types the information about employee.
    activate System

    System --> Employee : Generate a password to the new employee \nand displays operation success.
            deactivate System
@enduml