@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administrator" as Employee
participant ":System" as System

    Employee -> System : ask to register a new employee.
    activate System

        System --> Employee : show a list of the role of the employee (agent, store manager, store network manager).

    deactivate System

    Employee -> System : select the role of the employee.
    activate System

    System --> Employee : show a list of agencies.
       deactivate System

        Employee -> System : select the agency.
        activate System

        System --> Employee : request information about employee (employeeName, passaportCardNumber, \nemployeeTaxNumber, employeeAddress, employeeEmail , employeePhoneNumber).
    deactivate System

    Employee -> System : types the information about employee.
    activate System

    System --> Employee : Ask to confirm the operation.
           deactivate System

            Employee -> System : Confirms.
            activate System

    System --> Employee : Send a generated password to the employeeEmail and displays operation success.
            deactivate System

@enduml