@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to view the available announcements

    activate System

        System --> Agent : shows the announcements

    deactivate System

    Agent -> System : selects one of the announcements

    activate System

        System --> Agent : requests type of comission

    deactivate System

    Agent -> System : inserts type of comission

    activate System

        System --> Agent : requests the comission

    deactivate System

    Agent -> System : inserts comission

    activate System

        System --> Agent : shows all the information for confirmation

    deactivate System

    Agent -> System : confirms the information

    activate System

        System --> Agent : publishes announcement

    deactivate System

deactivate Agent

@enduml