@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 004

autonumber

actor "Owner" as Owner
participant ":System" as System

activate Owner

    Owner -> System : asks to create a new request
    activate System

        System --> Owner : shows agency list and asks to select one
    deactivate System

    Owner -> System : selects an agency
    activate System

        System --> Owner : shows agents list and asks to select one
    deactivate System

    Owner -> System : selects an agent
    activate System


        System --> Owner : ask to select the type of property
    deactivate System

    Owner -> System : selects the type of property

        activate System

        System --> Owner : requests data (area (m2), location, distance from the city centre)

    deactivate System

    Owner -> System : inserts data

    activate System

    System --> Owner : asks for property photos
    deactivate System

    loop at least 1 photo and at most 30 photos

    Owner -> System : inserts property photos (URI)
    activate System

    end

    System --> Owner : ask for the type of business (rent or sell)
    deactivate System


    Owner -> System : inserts type of business
   activate System

    opt Property is Apartment or House

        System --> Owner : requests data (number of bedrooms, number of bathrooms, \nnumber of parking spaces and available equipment)

    deactivate System

    Owner -> System : inserts data
    activate System

    opt Property is a House

         System --> Owner : requests data (existence of a basement and/or inhabitable loft and sun exposure)
    deactivate System

    Owner -> System : inserts data
    activate System

    end

    end

    System --> Owner : request the type of operation (sell or rent)
    deactivate System

    Owner -> System : inserts type of operation

    alt the owner intends to rent a property
    activate System

    System --> Owner : asks for the contract duration and the price (per month)
    deactivate System

    Owner -> System : submits data
    activate System

    else the owner intends to sell a property
    System --> Owner : asks for the property price

    deactivate System

    Owner -> System : submits data
    activate System

    end

          System --> Owner : requests data (name, passport number, tax number, address, email address, telephone number)
    deactivate System

    Owner -> System : Inserts data
    activate System

           System --> Owner : shows requested data, selected property movement and asks for confirmation

    deactivate System

    Owner -> System : confirm data
    activate System

            System --> Owner : shows operation success
    deactivate System

@enduml