@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 004

autonumber

actor "Owner" as Owner
participant ":System" as System

activate Owner

    Owner -> System : asks to create a new request

    activate System

    System --> Owner : shows the type of property list and asks to select one

    deactivate System

    Owner -> System : selects a type of property

    activate System

    System --> Owner : requests data(area distanceFromCityCentre, price)

    deactivate System

    Owner -> System : inserts data

    activate System

    System --> Owner : shows list of states and asks to select one

    deactivate System

    Owner -> System : selects a state

    activate System

    System --> Owner : shows list of districts and asks to select one

    deactivate System

    Owner -> System : selects a district

    activate System

    System --> Owner : show list of cities and asks to select one

    deactivate System

    Owner -> System : selects a city

    activate System

    System --> Owner : requests data (door number, floor number, street address)

    deactivate System

    Owner -> System : inserts data

    activate System

    System --> Owner : requests the number of photos that the owner intends to submit

    deactivate System

    Owner -> System : inserts the number of photos

    activate System

    loop from 1 to the number of photos defined

    System --> Owner : asks for the photos URI

    deactivate System

    Owner -> System : inserts photos URI

    activate System

    end

    System --> Owner : shows type of request list and asks to select one

    deactivate System

    Owner -> System : selects the type of request

    activate System

    opt Rent a Property

    System --> Owner : requests data (contract duration)

    deactivate System

    Owner -> System : inserts data

    activate System

    end

    opt Property is Apartment or House

    System --> Owner : requests data (number of bedrooms, number of bathrooms, \nnumber of parking spaces and available equipment)

    deactivate System

    Owner -> System : inserts data

    activate System

    opt Property is a House

    System --> Owner : requests data (existence of a basement, inhabitable loft and sun exposure)

    deactivate System

    Owner -> System : inserts data

    activate System

    end

    end

    System --> Owner : shows agencies list and asks to select one

    deactivate System

    Owner -> System : selects an agency

    activate System

    System --> Owner : shows agents list and asks to select one

    deactivate System

    Owner -> System : selects an agent

    activate System

    System --> Owner : shows operation success

    deactivate System

@enduml