@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

hide circle
hide methods

title US013 Domain Model

class NetworkManager {
}

class Employee {
}

class Store {
}


NetworkManager "1" -- Employee



@enduml