@startuml
autonumber
title US018 - Sequence Diagram (SD)
actor StoreManager as SM

participant ":DealsAnalyzesUI" as GUI
participant ":DealsAnalyzesController" as CTRL
participant ":Repositories" as REPO
participant "repositories :Repositories" as repo
participant ":FileInformation" as IF

participant ":OrderRepository" as OR
participant ":Order" as O

participant ":SimpleRegression" as SR
participant ":MultipleLinearRegression" as MLR

activate SM

    SM -> GUI: asks to analyse the deals (on houses and apartments)
    activate GUI
        SM <-- GUI: requests the path of the information file
        SM -> GUI: inserts the path of the information file

        GUI -> CTRL**: create()
        GUI -> CTRL: informationFromFile(path)
        activate CTRL

            CTRL -> REPO: getInstance
            activate REPO
                CTRL <-- REPO: repositories
            deactivate REPO
            CTRL -> repo: getOrderRepository
            activate repo
                CTRL <-- repo: OrderRepository
            deactivate repo
            CTRL -> IF: loadDealsFromFile(path)
            activate IF

                CTRL <-- IF: list<InformationFromFile>
            deactivate IF

            CTRL -> CTRL: fillAdvertisementInfo()
            activate CTRL

            deactivate CTRL

            CTRL -> OR: createOrder(list<Advertisement> advertisementList)
            activate OR

loop for each announcement
                OR -> O**: createOrder()
end
                CTRL <-- OR: List<Order> acceptedOrders
            deactivate OR

            GUI <-- CTRL: List<Order> acceptedOrders

        deactivate CTRL

        deactivate CTRL

        SM <-- GUI: shows regression models and requests to select one (simple-linear or multi-linear)
        SM -> GUI: selects a regression model (simple-linear or multi-linear)
        GUI --> SM: asks for the parameter to be used (eg. area, number of bathrooms, etc...)
        SM -> GUI : selects a parameter (eg. area, number of bathrooms, etc...)

        GUI -> CTRL: getPrediction(selectedParameter(s))
        alt if simple-linear regression model is selected
        activate CTRL

            CTRL -> SR: simplePrediction(selectedParameter)
            activate SR

                SR --> CTRL: prediction

                deactivate SR

            else if multi-linear regression model is selected

                CTRL -> MLR: multiPrediction(selectedParameter(s))
                activate MLR

                    MLR --> CTRL: prediction

                    deactivate MLR

            end

            CTRL --> GUI: prediction

    deactivate CTRL

        SM <-- GUI: displays the prediction

    deactivate GUI


@enduml