@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

title US018 - Class Diagram (CD)


class DealsAnalysisUI {
}

class DealsAnalysisController {
    +create()
    +simpleLinearRegression(option)
    +multiLinearRegression(option)
    +receiveDescriptiveStats(descriptiveStats)
}

class OrderRepository {
- List<Order> order
    + addNewOrder(order)
    + validateOrder(announcement, orderPrice)
    + valid(order)
    + getOrders()
    + getOrdersByAnnouncement(announcement)
    + add(order)
}


class Announcements {
    +getSimpleParameterList(option)
    +getAllParameterList()
    +getAnnouncementValues()
}

class SimpleLinear {
    - regression: SimpleRegression
    - n: int
    - Sxx: double
    - Syy: double
    - Sxy: double
    - SE: double
    - SR: double
    - avgX: double
    - avgY: double
    - slope: double
    - intercept: double
    - squareR: double
    + getCoefficients(): double[]
    + toString(): String
    + anovaSingificanceModel()
    + calculateInterceptConfidenceInterval()
    + calculateSlopeConfidenceInterval()
    + calculateInterceptHyopthesisTest()
    + calculateSlopeHyopthesisTest()
    + generateAnalysisReport()
}


class SimpleLinearRegression {
    +getRegressionModel(parameterList)
}

class MultiLinearRegression{
    +getRegressionModel(parametersList)

}
class MultiLinear {
    - regression: OLSMultipleLinearRegression
    - parameters: double[][]
    - n: int
    - B: double[]
    - k: int
    - SE: double
    - ST: double
    - SR: double
    - squareR: double
    - squareRAdjusted: double
    - parametersStdErr: double[]
    + getB()
    + anovaSingificanceModel()
    + calculateCoefficientCondifenceIntervals()
    + calculateHypothesisTests()
    + generateAnalysisReport()
}

class Repositories {
  - Repositories()
  +getInstance() : Repositories
  +getOrderRepository()
}
class AnnouncementRepository{
  + getAnnouncements()
}

Repositories --> OrderRepository : OrderRepository
DealsAnalysisController -.-> Repositories : repositories
DealsAnalysisController -.-> SimpleLinearRegression : simpleLinearRegression
DealsAnalysisController -.-> MultiLinearRegression : multiLinearRegression
DealsAnalysisController -.-> AnnouncementRepository : announcementRepository
AnnouncementRepository --> "*" Announcements : announcements
Repositories -> Repositories : instance
DealsAnalysisController -.-> OrderRepository : orderRepository
MultiLinearRegression ..> MultiLinear
DealsAnalysisUI ..> DealsAnalysisController
DealsAnalysisController ..> Announcements
SimpleLinearRegression ..> SimpleLinear
@enduml