@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Owner" as ADM
participant ":CreateRequestUI" as UI
participant ":CreateRequestController" as CTRL
participant ":Repositories" as Rep
participant "repositories\n:Repository" as PLAT
participant "PropertyTypeListRepository" as PTLR
participant "agencyRepository\n:AgencyRepository" as agencyRepository
participant "requestTypeRepository:\nRequestTypeRepository" as RequestRepository
participant "property: \nProperty" as property
participant "residence: \nResidence" as residence
participant "house: \nHouse" as house
participant "request: \nRequest" as Req
participant "photograph: \nPhotograph" as Photo
participant "photographList" as PhotoList
participant "addressRepository:\nAddressRepository" as address

activate ADM

        ADM -> UI : asks to create a new request

        activate UI

            UI -> CTRL** : create

            UI -> CTRL : getPropertyTypeList()
            activate CTRL

                CTRL -> Rep : getInstance()
                activate Rep

                    Rep --> CTRL: repositories
                deactivate Rep

                CTRL -> PLAT : getPropertyTypeListRepository()
                activate PLAT

                    PLAT --> CTRL: requestRepository
                deactivate PLAT

                CTRL -> PTLR : getPropertyTypeList()
                activate PTLR

                PTLR --> CTRL : propertyTypeList
                deactivate PTLR

                CTRL --> UI : propertyTypeList
            deactivate CTRL

            UI --> ADM : shows the type of property list and asks to select one
        deactivate UI

    ADM -> UI : selects a type of property
    activate UI

    UI -> CTRL : setPropertyType(propertyType)

    activate CTRL

    CTRL --> UI : propertyType selected

    deactivate CTRL

    UI --> ADM : requests data (area, distance from the city center, price)

    deactivate UI

    ADM -> UI: inserts data

    activate UI

   UI -> CTRL : getState()
               activate CTRL

                       CTRL -> Rep : getInstance()
                       activate Rep

                       Rep --> CTRL: repositories
                       deactivate Rep

                       CTRL -> PLAT : getStateRepository()

                       activate PLAT

                       PLAT --> CTRL : statesRepository

                       deactivate PLAT

                       CTRL -> address : getStateList()

                       activate address

                       address --> CTRL : stateList

                       deactivate address

               CTRL --> UI : stateList
               deactivate CTRL

    UI --> ADM : shows list of states and asks to select one
                deactivate UI

                ADM -> UI : selects a state
                activate UI

                UI -> CTRL : getDistrict()
                activate CTRL

                        CTRL -> Rep : getInstance()
                        activate Rep

                        Rep --> CTRL: repositories
                        deactivate Rep

                        CTRL -> PLAT : getDistrictRepository

                        activate PLAT

                        PLAT --> CTRL : districtRepository

                        deactivate PLAT

                        CTRL -> address : getDistrictList
                        activate address

                        address --> CTRL : districtList
                        deactivate address


                CTRL --> UI : districtList
                deactivate CTRL

                UI --> ADM : shows list of districts and asks to select one
                deactivate UI

                ADM -> UI : selects a district
                activate UI

                UI --> CTRL : getCity()
                activate CTRL

                    CTRL -> Rep : getInstance()
                    activate Rep

                    Rep --> CTRL: repositories
                    deactivate Rep

                    CTRL -> PLAT : getCityRepository
                    activate PLAT

                    PLAT --> CTRL : cityRepository
                    deactivate PLAT

                    CTRL -> address : getCityList

                    activate address

                    address --> CTRL : cityList

                    deactivate address

                CTRL --> UI : cityList
                deactivate CTRL

                UI --> ADM : show list of cities and asks to select one
                deactivate UI

                ADM -> UI: selects a city

                activate UI

                UI --> ADM : requests data (door number, floor number, zip code, street address)

                deactivate UI

                ADM -> UI : inserts data
                activate UI

                        UI -> CTRL :createAddress(doorNumber, floorNumber, zipCode, streetAddress, city, district, state)
                        activate CTRL

                        CTRL -> Address : createAddress(doorNumber, floorNumber, zipCode, streetAddress, city, district, state)
                        activate Address

                        Address --> CTRL : address
                        deactivate Address

                        CTRL --> UI : address
                        deactivate CTRL

    UI --> ADM :  request the number of photos that the owner intends to submit

    deactivate UI

    ADM -> UI : inserts the number of photos

    activate UI

    loop from 1 to the number of photos defined
    UI --> ADM : asks for the photos URI

    deactivate UI

    ADM -> UI : inserts photo URI
    activate UI

    UI -> CTRL : createPhotograph(URI)
    activate CTRL

            CTRL -> Photo: createPhotograph(URI)
            deactivate CTRL

            activate Photo

    Photo -> PhotoList : addPhotographToPhotoList

    activate PhotoList

    PhotoList --> Photo : photoList

    deactivate PhotoList

    Photo --> CTRL : photoList

    deactivate Photo

    activate CTRL

    CTRL --> UI : photoList

    deactivate CTRL

    end

    UI -> CTRL : getRequestTypeList()
                activate CTRL

                    CTRL -> Rep : getInstance()
                    activate Rep

                        Rep --> CTRL: repositories
                    deactivate Rep

                    CTRL -> PLAT : getRequestTypeRepository()
                    activate PLAT

                        PLAT --> CTRL: requestRepository
                    deactivate PLAT

                    CTRL -> RequestRepository : getRequestTypeList()

                    activate RequestRepository

                    RequestRepository --> CTRL : requestTypeList
                    deactivate RequestRepository

                    CTRL --> UI : requestTypeList
                deactivate CTRL


    deactivate CTRL

   UI --> ADM : shows type of request list and asks to select one

   deactivate UI

   ADM -> UI : selects the type of request

   activate UI

   UI -> CTRL : setRequestType(requestType)

   activate CTRL

   CTRL -->  UI : RequestType selected

   deactivate CTRL

    opt Rent a Property

    UI-->ADM : request data (contract duration)
    deactivate UI

    ADM -> UI : inserts data

    activate UI

    deactivate CTRL
    end

    UI -> CTRL : CreateProperty(area, distanceFromCityCenter, address, price)

    activate CTRL

    CTRL -> property : CreateProperty(area, distanceFromCityCenter, address, price)

    activate property

    property --> CTRL : property

    deactivate property

    CTRL --> CTRL : addProperty(property)

    deactivate CTRL

    opt Property Apartment or House

    UI--> ADM : request data(number of bedrooms, number of bathrooms, \nnumber of parking spaces and availableEquipment)
    deactivate UI

    ADM -> UI : inserts data
    activate UI

    UI -> CTRL : CreateResidence(numberOfBedrooms, numberOfBathrooms, numberOfParkingSpaces, availableEquipment)

    activate CTRL

    CTRL -> residence : CreateResidence(numberOfBedrooms, numberOfBathrooms, numberOfParkingSpaces, availableEquipment)

    activate residence

    residence --> CTRL : residence

    deactivate residence

    CTRL --> CTRL : addProperty(residence)

    deactivate CTRL

    opt Property is a House

    UI --> ADM : request data (existence of a basement, inhabitable loft and sun exposure)

    deactivate UI
    ADM-> UI : inserts data

    activate UI

    UI -> CTRL : CreateHouse(existenceOfBasement, inhabitableLoft, sunExposure)

    activate CTRL

    CTRL -> house : CreateHouse(existenceOfBasement, inhabitableLoft, sunExposure)

    activate house

    house --> CTRL : house

    deactivate house

    CTRL --> CTRL : addProperty(house)

    deactivate CTRL

    end

    end

    UI -> CTRL : getAgency()

    activate CTRL

                        CTRL -> Rep : getInstance()
                        activate Rep

                            Rep --> CTRL: repositories
                        deactivate Rep

                        CTRL -> PLAT : getAgencyRepository()
                        activate PLAT

                            PLAT --> CTRL: agencyRepository
                        deactivate PLAT

                        CTRL -> agencyRepository : getAgencyList()

                        activate agencyRepository

                        agencyRepository --> CTRL : agencyList
                        deactivate agencyRepository

                        CTRL --> UI : agencyList
                    deactivate CTRL

        deactivate CTRL

    UI --> ADM : shows agency list and asks to select one
    deactivate UI
    ADM -> UI : selects an agency
    activate UI

     UI -> CTRL : getAgent()

        activate CTRL

                            CTRL -> Rep : getInstance()
                            activate Rep

                                Rep --> CTRL: repositories
                            deactivate Rep

                            CTRL -> PLAT : getAgencyRepository()
                            activate PLAT

                                PLAT --> CTRL: agencyRepository
                            deactivate PLAT

                            CTRL -> agencyRepository : getAgentsList()

                            activate agencyRepository

                            agencyRepository --> CTRL : agentsList
                            deactivate agencyRepository

                            CTRL --> UI : agentsList
                        deactivate CTRL

            deactivate CTRL

    UI --> ADM : shows agents list and asks to select one
    deactivate UI

    ADM -> UI : selects an agent

    activate UI

    UI -> CTRL : createRequest(propertyType, requestType, agency, agent, currentDate, photoList)

    activate CTRL

    CTRL -> Req : createRequest(propertyType, requestType, agency, agent, currentDate, photoList)

    activate Req

    Req --> CTRL : request

    deactivate Req

    CTRL --> CTRL : addRequest(request)

    deactivate CTRL

    UI --> ADM : shows operation success
    deactivate UI
    deactivate ADM
    @enduml