@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
title Sequence Diagram (SD) - US 004
'hide footbox
actor "Owner" as Owner
participant ":CreateRequestUI" as UI
participant ":CreateRequestController" as CTRL
participant ":Repositories" as Repositories
participant "repositories:\nRepositories" as RR
participant "agencyRepository:\nAgencyRepository" as AgencyR
participant "agentsRepository:\nAgentsRepository" as AgentR
participant "requestRepository:\nAnnouncementRepository" as RR
participant "propertyRepository:\nPropertyRepository" as PR
participant "businessRepository:\nBusinessRepository" as BR

activate Owner

        Owner -> UI : asks to create a new request

        activate UI

            UI -> CTRL** : getAgencyList
            activate CTRL

                CTRL -> Repositories : getInstance()
                activate Repositories

                    Repositories --> CTRL: repositories
                deactivate Repositories

                CTRL -> RR : getAgencyRepository()
                activate RR

                    RR --> CTRL: agencyRepository
                deactivate RR

                CTRL ->  AgencyR : getAgencies()
                activate AgencyR

                    AgencyR --> CTRL : agencyList
                deactivate AgencyR

                CTRL --> UI : agencyList
            deactivate CTRL

            UI --> Owner : shows agency list\n and asks to select one

            Owner -> UI : selects an agency

            UI -> CTRL : getAgentsList()
            activate CTRL

            CTRL -> RR : getAgentsRepository()
            activate RR

            RR --> CTRL : agentsRepository

            deactivate RR

            CTRL -> AgentR : getAgents()
            activate AgentR

            AgentR --> CTRL : agentsList
            deactivate AgentR

            CTRL --> UI : agentsList
            deactivate

            deactivate CTRL

            UI --> Owner : shows agents list, \n and asks to select one

            Owner -> UI : selects an agent

            UI --> Owner : shows type of property \nand asks to select one

            UI -> CTRL : getPropertyTypesList()
            activate CTRL

            CTRL -> RR : getPropertyTypesListRepository()
            activate RR

            RR --> CTRL : propertyTypesRepository
            deactivate RR

            CTRL -> PR : getPropertyTypes()
            activate PR

            PR --> CTRL : propertyTypesList
            deactivate PR
            CTRL --> UI : propertyTypesList
            deactivate CTRL

            Owner -> UI : selects the type of property

            UI -> CTRL : set

            UI --> Owner : requests data (area(m^2), location, distance from the city centre)

            Owner -> UI : inserts data

            UI -> UI : save provided data

            UI --> Owner : asks for the number of property photos \nthat the owner intends to insert

            Owner -> UI : inserts the number of photos

            loop from 1 to the number defined by the owner

            Owner -> UI : inserts property photos (URI)

            UI -> UI : save provided data

            end

    opt Property is Apartment or House

        UI --> Owner : requests data (number of bedrooms, number of bathrooms, \nnumber of parking spaces and available equipment)

    Owner -> UI : inserts data

    UI -> UI : save provided data

    opt Property is a House

         UI --> Owner : requests data (existence of a basement and/or inhabitable loft and sun exposure)

    Owner -> UI : inserts data

    UI -> UI : save provided data

    end

    end

    UI --> Owner : shows the type of operation list and asks to select one
    UI -> CTRL : getTypesOfOperationList()
    activate CTRL

    CTRL -> RR : getTypesOfOperationRepository()
    activate RR

    RR --> CTRL : typesOfOperationRepository
    deactivate RR

    CTRL -> BR : getTypesOfOperation()
    activate BR

    BR --> CTRL : typesOfOperationList
    deactivate BR

    CTRL --> UI : typeOfOperationList
    deactivate CTRL

    Owner -> UI : inserts type of operation

    alt the owner intends to rent a property

    UI --> Owner : asks for the contract duration and the price (per month)

    Owner -> UI : submits data

    UI -> UI : save provided data

    else the owner intends to sell a property
    UI --> Owner : asks for the property price

    Owner -> UI : submits data

    UI -> UI : submits provided data

    end
          UI --> Owner : requests data (name, passport number, tax number, address, email address, telephone number)

    Owner -> UI : Inserts data

    UI -> UI : submits provided data

           UI --> Owner : shows requested data, selected property movement and asks for confirmation

            Owner -> UI : confirms data
            deactivate CTRL
            UI --> Owner: shows operation success
    deactivate UI

deactivate Owner
@enduml