@startuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
'skinparam linetype orto

class CreateRequestUI{
}

class CreateRequestController{
+getPropertyTypeList()
+setPropertyType(propertyType)
+getState()
+getDistrict()
+getCity()
+createAddress(doorNumber, floorNumber, zipCode, streetAddress, city, district, state)
+createPhotograph(URI)
+getRequestTypeList()
+setRequestType(requestType)
+createProperty(area, distanceFromCityCenter, address, price)
+createHouse(existenceOfBasement, inhabitableLoft, sunExposure)
+getAgency()
+getAgent()
+createRequest(propertyType, requestType, agency, agent, currentDate, photoList)
}

class Repositories{
+getInstance()
+getPropertyTypeRepository()
+getStateRepository()
+getRequestTypeRepository()
+getAgencyRepository()
}

class PropertyTypeListRepository{
+getPropertyTypeList()
}

class AgencyRepository{
+getAgencyList()
+getAgentsList()
}

class Property{
+createProperty(area, distanceFromCityCenter, address, price)
}

class Residence{
+createResidence(numberOfBedrooms, numberOfBathrooms, numberOfParkingSpaces, availableEquipment)
}

class House{
+createHouse(existenceOfBasement, inhabitableLoft, sunExposure)
}

class Photograph{
+createPhotograph(URI)
}

class PhotographList{
+addPhotographToPhotoList()
}

class AddressRepository{
+getStateList()
+getDistrictList()
+getCityList()
}

class RequestTypeRepository{
+getRequestTypeList()
}

class Address{
+createAddress(doorNumber, floorNumber, zipCode, streetAddress, city, district, state)
}

class Request{
+createRequest(propertyType, requestType, agency, agent, currentDate, photoList)
}

CreateRequestUI -.-> CreateRequestController

CreateRequestController --> Repositories
CreateRequestController -.-> RequestTypeRepository
CreateRequestController -.-> PropertyTypeListRepository
CreateRequestController -.-> AgencyRepository
CreateRequestController -.-> AddressRepository

Repositories --> RequestTypeRepository
Repositories --> PropertyTypeListRepository
Repositories --> AgencyRepository
Repositories --> AddressRepository

AddressRepository --> Address

CreateRequestController --> Property
CreateRequestController --> Residence
CreateRequestController --> House

Residence --|> Property

House --|> Residence



@enduml