@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class SystemAdministrator {
}

class employeeAddress{
-String street
-Integer doorNumber
-String city
-String state
-Integer zipCode
-String country
}
 class RegisterEmployeeUI{

 }
 class RegisterEmployeeController{
getAgencies()
 }
class Employee {
    -String EmployeeName
    -String EmployeeEmail
    -Integer EmployeePhoneNumber
    -Integer TaxNumber
    -Integer passportCardNumber

}

class Agency {

}

SystemAdministrator "1"--"0...*" Employee: registe >
SystemAdministrator --|> Employee: is an
Employee --|> employeeAddress

Employee "1"--"1" Agency: works for >
Employee "0...*"--"1...*" Role: has >

@enduml