@startuml
skinparam classAttributeIconSize 0

class RegisteremployeeController{
    -getAgencies()
    -getEmployeeRoles()
    -getStores()
    -registerEmployee(data)
}

class Repositories{
    getInstance() : Repositories
    -getAgencyRepositories()
    -getRoleRepositories()
    -getStoreRepositories()
}

class AgencyRepository{
    -getAllAgencies()
}

class RoleRepository{
    -getEmployeeRoles()
}

class StoreRepository{
    -getAllAgencyStores(agency)
}

class passwordGenerator{
    -generate()
}

class emailService{
    -sendRegisteredUserEmail(employee.email(), employee.password())
}

class user{
-register(data, role, pass)
}

class userRepository{
-save(user)
}

class RegisterEmpployeeUI{
}




class Employee {
    -String email
    -String telephone_number
    -String agency
    -String name
    -String citize_number
    -String tax_number

}

class Address {
    -String City
    -String Street
    -String District
    -String State
    -double Zipcode
}

class Role{
    - String description
    - String permissions
}

class Store{
    -String designation
    }


class Password {
    -String password
}



RegisterEmpployeeUI .>RegisteremployeeController
RegisteremployeeController .>Repositories :repositories
RegisteremployeeController .>AgencyRepository
RegisteremployeeController .>RoleRepository
RegisteremployeeController .>StoreRepository
RegisteremployeeController .>passwordGenerator
RegisteremployeeController .>emailService






Address --|> Employee: has an
SystemAdministrator "1"--"0...*" Employee: registe >
Employee --|> SystemAdministrator: is an <
Employee "1"--"1" Password: sent to <
Employee "1"<|--"1" Store: works for >
Employee "1"<|--"1" Role: has >
SystemAdministrator -- Password: give a >
@enduml