@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant "RegistNewEmployeeUI" as UI
participant ":RegistNewEmployeeController" as CTRL
participant ":RoleRepository" as RoleREPO
participant ":EmployeeRepository" as EmployREPO
participant "Adress" as ADR
participant "AgencyRepository" as AGENCY
participant "IncompleteEmployee" as IncEmploy
participant "EmployeeEmail" as EMAIL

activate ADM

ADM -> UI : ask to register a new employee.

activate UI

UI -> CTRL : registerNewEmployee()

activate CTRL

CTRL -> RoleREPO : getRoleList()
activate RoleREPO

RoleREPO --> CTRL : roleList
deactivate RoleREPO

CTRL --> UI : showRoleList(roleOptions)
            deactivate CTRL

UI --> ADM : selectRole()
ADM -> UI : selectedRole(role)

UI -> CTRL : setRole(role)
activate CTRL

CTRL --> UI : role
deactivate CTRL



UI --> ADM : requestEmployeeInformation(employeeName, employeeAddress, EmployeeEmail, \nemployeePhoneNumber, employeeTaxNumber, employeeAgency, passportCardNumber)
ADM -> UI : e \nemployeePhoneNumber, employeeTaxNumber, employeeAgency, passportCardNumber)
UI --> CTRL :setEmployeeInformation(employeeName, employeeAdress, EmployeeEmail, \nemployeePhoneNumber, employeeTaxNumber, employeeAgency, passportCardNumber)
activate CTRL

CTRL -> ADR : creatAddress(street, doorNumber, city, state, zipCode, country)

activate ADR

ADR --> CTRL : Address
deactivate ADR

CTRL -> AGENCY : agencyList()
activate AGENCY

AGENCY --> CTRL :agencyList
deactivate AGENCY

CTRL -> UI : showAgencyList(agencyList)

UI --> ADM : selectAgency()

ADM -> UI : selectedAgency(agency)

UI -> CTRL : setAgency(agency)

CTRL -> IncEmploy : createIncompleteEmployee(employeeName, employeeTaxNumber, nemployeePhoneNumber, employeeEmail, passportCardNumber)
activate IncEmploy

IncEmploy --> CTRL : IncompleteEmployee
deactivate IncEmploy

CTRL -> EmployREPO : createEmployee( IncompleteEmployee, role, agency, address)
activate EmployREPO

EmployREPO --> CTRL : newEmployee
deactivate EmployREPO

CTRL -> EMAIL : generatePassword(password)
activate EMAIL

EMAIL --> CTRL : operation sucess
deactivate EMAIL

CTRL -> UI : operationSucess

UI --> ADM : displays operation sucess
deactivate UI

deactivate ADM

@enduml