@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US017 - System Sequence Diagram (SSD)

autonumber

actor "Network Manager" as NM
participant ":System" as System

activate NM

    NM -> System : asks to list all the deals made

    activate System

        System --> NM : shows the list and asks to select one of the \nsorting methods (Bubble Sort or Insertion Sort)

    deactivate System

    NM -> System : selects the sorting method

    activate System

    System --> NM : asks for the order of sorting (ascending or descending)

    deactivate System

    NM -> System : selects the order of sorting (ascending or descending)

    activate System

    System --> NM : shows the list of all the deals made sorted by the \nselected sorting method and sorting order

    deactivate System

@enduml