@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant "RespondBookingRequestUI" as UI
participant ":RespondBookingRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "bookingRequestRepository:\nBookingRequestRepository" as BookingRequestRepository
participant "booking:\nBooking" as Booking
participant "bookingRepository:\nBookingRepository" as BookingRepository

activate ADM

        ADM -> UI : Asks to see the list of all booking requests

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getBookingRequest()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getBookingRequestRepository()
                activate PLAT

                    PLAT --> CTRL: bookingRequestRepository
                deactivate PLAT

                CTRL -> BookingRequest : getBookingRequest()
                activate BookingRequest

                   BookingRequest --> CTRL : bookingRequestList
                deactivate BookingRequest

                CTRL --> UI : bookingRequestList
            deactivate CTRL

            UI --> ADM : Shows the list off all booking requests and \n and asks to sleect one
        deactivate UI

    ADM -> UI : Selects a booking request and asks to select the option to respond
    activate UI

        UI --> ADM : Asks to accept or decline the booking request
    deactivate UI

    ADM -> UI : Accepts or declines
    activate UI

    UI --> ADM : Informs about the success of the operation

    deactivate UI

    alt if the booking request was rejected




   ADM -> UI : Rejected booking request

   activate UI

   UI -> CTRL : sendEmailBookingRequestRejected(requestId)



   activate CTRL

   CTRL -> bookingRequestRepository: getBookingRequestById(requestId)

   activate bookingRequestRepository

   bookingRequestRepository --> CTRL : bookingRequest

   deactivate bookingRequestRepository


   CTRL -> EmailService : sendEmailBookingRequestRejected(bookingRequest)


   activate EmailService

   EmailService --> CTRL :



   deactivate EmailService

    else if the booking request was accepted

    ADM -> UI : Accepted booking request



       UI -> CTRL : sendEmailBookingRequestAccepted(requestId)

      CTRL -> bookingRequestRepository: getBookingRequestById(requestId)

       activate bookingRequestRepository

       bookingRequestRepository --> CTRL : bookingRequest

       deactivate bookingRequestRepository





    CTRL -> EmailService : sendEmailBookingRequestAccepted(bookingRequest)

    activate EmailService

    EmailService --> CTRL :

    deactivate EmailService

    CTRL -> Booking** : create(bookingRequest)

    CTRL -> BookingRepository : save(booking)

    activate BookingRepository

    BookingRepository --> CTRL :

    deactivate BookingRepository



    end

    CTRL --> UI:

    deactivate CTRL

    UI --> ADM : Informs about the success of the operation

    deactivate UI


@enduml