@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant "RespondBookingRequestUI" as UI
participant ":RespondBookingRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "MessageRepository:\nMessageRepository" as MessageRepository
participant "Message" as Message
participant "bookingRepository:\nBookingRepository" as BookingRepository

activate ADM

        ADM -> UI : Asks to see the list of all booking requests

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getBookingRequest()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getMessageRepository()
                activate PLAT

                    PLAT --> CTRL: MessageRepository
                deactivate PLAT

                CTRL -> Message : getMessage()
                activate Message

                   Message --> CTRL : bookingRequestList
                deactivate Message

                CTRL --> UI : bookingRequestList
            deactivate CTRL

            UI --> ADM : Shows the list off all booking requests and \n and asks to sleect one
        deactivate UI

    ADM -> UI : Selects a booking request and asks to select the option to respond
    activate UI

        UI --> ADM : Asks to accept or decline the booking request
    deactivate UI

    ADM -> UI : Accepts or declines
    activate UI

    UI --> ADM : Informs about the success of the operation

    deactivate UI

    alt if the booking request was rejected




   ADM -> UI : Rejected booking request

   activate UI

   UI -> CTRL : sendEmailBookingRequestRejected(requestId)



   activate CTRL

   CTRL -> MessageRepository: getBookingRequestById(requestId)

   activate MessageRepository

   MessageRepository --> CTRL : bookingRequest

   deactivate MessageRepository


   CTRL -> SendEmailMessage : sendEmailBookingRequestRejected(bookingRequest)


   activate SendEmailMessage

   SendEmailMessage --> CTRL :



   deactivate SendEmailMessage

    else if the booking request was accepted

    ADM -> UI : Accepted booking request



       UI -> CTRL : sendEmailBookingRequestAccepted(requestId)

      CTRL -> MessageRepository: getBookingRequestById(requestId)

       activate MessageRepository

       MessageRepository --> CTRL : message

       deactivate MessageRepository


    CTRL -> SendEmailMessage : sendEmailBookingRequestAccepted(bookingRequest)

    activate SendEmailMessage

    SendEmailMessage --> CTRL :

    deactivate SendEmailMessage

    CTRL -> Booking** : create(bookingRequest)

    CTRL -> MessageRepository : save(booking)

    activate MessageRepository

    MessageRepository --> CTRL :

    deactivate MessageRepository



    end

    CTRL --> UI:

    deactivate CTRL

    UI --> ADM : Informs about the success of the operation

    deactivate UI


@enduml