@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant "RespondBookingRequestUI" as UI
participant ":RespondBookingRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "MessageRepository:\nMessageRepository" as MessageRepository
participant "Message" as Message

activate ADM

        ADM -> UI : Asks to see the list of all booking requests

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getMessage()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getMessageRepository()
                activate PLAT

                    PLAT --> CTRL: MessageRepository
                deactivate PLAT

                CTRL -> Message : getMessage()
                activate Message

                   Message --> CTRL : messageList
                deactivate Message

                CTRL --> UI : messageList
            deactivate CTRL

            UI --> ADM : Shows the list off all booking requests and \n and asks to sleect one
        deactivate UI

    ADM -> UI : Selects a booking request and asks to select the option to respond
    activate UI


    UI --> ADM : Informs about the success of the operation

    deactivate UI


    ADM -> UI : Responding to the booking request
    activate UI


       UI -> CTRL : replyMessage
       activate CTRL

      CTRL -> MessageRepository: getBookingRequest

       activate MessageRepository

       MessageRepository --> CTRL : message

       deactivate MessageRepository


    CTRL -> replyMessage : replyMessage(message)

    activate replyMessage

    replyMessage --> CTRL : writes message

    deactivate replyMessage


    CTRL -> MessageRepository : save(message)

    activate MessageRepository

    MessageRepository --> CTRL :

    deactivate MessageRepository

    CTRL --> UI:

    deactivate CTRL

    UI --> ADM : Informs about the success of the operation

    deactivate UI


@enduml