@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

hide circle
hide methods

title US001 Domain Model

class Adress{
street
city
doorNr
floorNr
state
postalCode
}

class District {
}

class Advertisement {
}

class Store{
}

Store "1"-- "*" Advertisement : displays >
Store "1" -- "1" Adress : has an >
Adress "1" -- "1" District : is in >
@enduml