@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

hide circle
hide methods

title US001 Domain Model

class Adress{
street
city
doorNr
floorNr
state
postalCode
}

class District {
}

class Announcement {
}

class Store {
}

class Property {
location
area
distanceFromCityCenter
photographs
}

class AvailableEquipment {
centralHeating
airConditioning
}

class SunExposure {
North
East
South
West
}

Store "1"-- "*" Announcement : displays >
Store "1" -- "1" Adress : has >
Adress "1" -- "1" District : is in >
Announcement "1" -- "1" Property : about >
Property "1" -- "1" AvailableEquipment : has >
Property "1" -- "1" SunExposure : has >
@enduml