@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

hide circle
hide methods

title Project domain Model



class PublishedAnnouncement {
photos
price
date
comissionType
comission
localDate
property
requestType
agent
price
store
}



class AvailableEquipment {
centralHeating
airConditioning
}

class Store {
    designation
    location
    localManager
    name
    ID
    phoneNumber
    emailAddress
}

class Agent {
    name
    citizenCardNumber
    tax number
    address
    email
    phoneNumber
    agency
}

class Property {
    area
    location
    distanceFromCityCentre
    requestedPrice
    typeOfProperty
    photographs
}



class Comission {
    fixed
    percentage
}

class User {
name
email
phone number
password
}
class Passport {
number
}
class TaxNumber {
number
}


class Agency {
designation
email
phone number
}


class Role {
description
permissions
}
class SystemAdministrator {
}
class StoreManager {
}

class StoreEmployee {
}

class AgencyEmployee {
}

class Owner{
name
emailAddress
phoneNumber
}


class CompanyStore{
ID
designation
emailAddress
phoneNumber
}

class Address{
doorNumber
floorNumber
postalCode
street
city
district
state
zipcode
}


class Photographs{
numberOfPhotographs
URI
}

class TaxNumber{
taxNumber
}


class SunExposure{
direction
}


class PassportCardNumber{
passportCardNumber
}

class District{
districtName
}



class City{
cityName
}

class Comission{
percentage
}

class Rent{
contractDuration
}

class RequestType{
requestTypeDescription
date
requiredPrice
requestType
price
agent
owner
store
requestDate
property
startDate
enDate
}




class State {
    stateName
}



class UnregisteredUser{
-String name

}


class AppartmentOrHouse {
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}





class Client{
name
phoneNumber
}


class ListOfAnnouncements{
annoucements
}


class Message{
 phone
 announcement
 newVisitStartTime
 newVisitEndTime
}




class Offer {
    offerPrice
    property
}


class Employee{
name
phoneNumber
emailAddress
taxNumber
passportCardNumber
}

class Decision{
decision
}

class Order{
orderNumber
clientEmail
price
announcement
}


class User{
name
phoneNumber
emailAddress
taxNumber
passportCardNumber
}



class EmailService{
informationEmail
}






class Residence{
numberOfBedrooms
numberOfBathrooms
numberOfParkingSpacings
airConditioning
centralHeating
finalPrice
businessDate
}

class House{
numberOfBedrooms
numberOfBathrooms
numberOfParkingSpacings
airConditioning
centralHeating
finalPrice
businessDate
existenceOfABasement
sunExposure
inhabitableLoft
}

class Legacy_System_Files {
}


class StoreManager{
assignedStore
}


class NetworkManager{
name
emailAddress
phoneNumber
}


class VisitRequest{
date
timeSlot
}



class Annoucement{
property
date
commissionType
commission
requestType
price
owner
}


class EmailResponse {
    emailTo
    emailFrom
    emailSubject
    emailBody
}

class Agent {
    name
    phoneNumber
    emailAddress
}



class Client {
      name
      phoneNumber
      emailAddress
      taxNumber
      passportCardNumber
}


class BookingRequest {
    visitDate

}



class Announcement{
comissionType
comission
date
}

class Client{
}





class NetworkManager{
}



class Client{
}






class NetworkManager{
}



class Client{
}


class House{
existenceOfABasement
inhabitableLoft
}





City "1" -- "1" Address : has >

State "1" -- "1" District : has >

District "1" -- "1" City : has >

PublishedAnnouncement "1" -- "1" Property : about >

Residence "1" -- "1" AvailableEquipment : has >

House "1" -- "1" SunExposure : has >
House --|> Residence : is a


Residence --|> House : extends


Property <|-- Residence
Property "1" -- "1" Address : located at >

Store "1" -- "*" Agent : has >
Store "1" -- "1" Address: has a >




Owner "1" --- "1" PassportCardNumber : has >
Owner "1" --- "1" TaxNumber : has >
Owner "1" -- "1" CompanyStore : selects >
Owner "1" --- "1" Address : has >
Owner "1" ---"0...*" Request : submits
Owner "1" ---"1" Agent : selects >
Owner --- Property : owns >
Owner "1" -- "*" Property : belongs to <


Announcement "1" - "1" Property : has >
Announcement "1" -- "1" Comission : has >
Announcement --> Request : contains
Announcement "1"--"1" Agent : has >
Announcement "1"--"1" VisitRequest : has <







Property "1" -- "1" AppartmentOrHouse : can be >
Property "1" -- "1" PropertyType : has a >
Property "1" --- "1...30" Photographs : has >
Property --|> Residence : contains

Request --> Property : contains
Property "1" -- "*" BookingRequest: has >
Address "1" -- "1" Property: has >






AppartmentOrHouse "1" - "1" House : can be >


Agent "1" - "1" Comission : defines >
Agent "1" -- "*" Announcement : creates >
Agent  --|>   StoreEmployee
Agent "*" -left- "1" Store : has an <
Agent "1" ---- "1" CompanyStore : works for >
Agent "1" --- "1" Address : has >
Agent "1" --- "1" PassportCardNumber : has >
Agent "1" --- "1" TaxNumber : has >
Agent --- Request : validates >
Agent "1" - "1" ListOfRequests : sees >
Agent "1" -- "*" VisitRequest : lists >
Agent -- Client: Informs >
(Agent, Client) -- EmailResponse: making use of
Agent "1" -- BookingRequest: decides >
Agent ---|> Employee : is >
Agent "1" -- "1...*" Order : makes the \ndecision on  >
Agent -- Store : works for >



BookingRequest "*" -- "1" Client: makes <




VisitRequest "1"--"*" Message : has >


User "1" -- "1" Passport: has a >
User "1" -- "1" TaxNumber: has a >
User "1" -- "1" Address: has an >
User "1" -left- "1" Role: has a >
User "1" -- "1...*" Order : makes


Agency "1" -right- "1" Store: has a >

SystemAdministrator  --|> Employee

StoreManager  --left|> StoreEmployee
StoreManager "1" -- "1" Store : manages >"
StoreManager -- Employee : is >



AgencyEmployee "1" -left- "1" Agency: runs >
AgencyEmployee --|> Employee


StoreEmployee "1" -right- "1" Store: belongs to >
StoreEmployee --|> AgencyEmployee

NetworkManager --|> AgencyEmployee
NetworkManager -- "*" Agent : lists >
NetworkManager --- "1...*" Order : sorts the deals >
NetworkManager --|> Employee : is >
NetworkManager "1" --- "1...*" Store : manages >
NetworkManager --- "1...*" Order : sorts the deals >





Employee --|> User
Employee "1" -- "*" Decision : makes >
Employee "1" --"*" Order : analyzes >



Request "1" -- "1" RequestType : has a >
Request "1" -- "1" Property : announces >
ListOfRequests "1" -- "*" Request : has >

Rent --- RequestType : can be <

Client "1" -- "1" ListOfAnnouncements : choose one of >
Client "1" -- "1" Message : send >
Client "1" -- "*" Offer : proposes >
Client -- Order : makes >
Client -- Address : has >


Message "1" -- "1" Agent : recive <

Offer "1" -up- "1" Request : is compared to >
Offer "1" -- "1" Property : about >

Order "*" -- "1" Announcement : > on



Decision "1" -- "1" Order : has <
Decision -- EmailService : depending on <

EmailService -- User : informing about the decision >
EmailResponse "1" -- "1" BookingRequest: about >


System_Administrator --> Legacy_System_Files

Legacy_System_Files "1" --> "0...*" Announcement : contains
















@enduml