@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":RegisterStoreUI" as UI
participant "controller\n:RegisterStoreController" as STRCTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "StoreRepository:\nStoreRepository" as StoreRepository
participant "StateRepository:\nStateRepository" as StateRepository
participant "DistrictRepository:\nDistrictRepository" as DistrictRepository
participant "CityRepository:\nCityRepository" as CityRepository
participant "Address:\nAddress" as Address
'participant ":ApplicationSession" as _APP
'participant "appSession\n:ApplicationSession" as APP
'participant "currentSession\n:UserSession" as SESSAO
'participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
'participant "organization\n:Organization" as ORG
participant "store\n:Store" as Store

activate ADM

        ADM -> UI : asks to register a store

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> STRCTRL** : create


            activate STRCTRL

                    STRCTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> STRCTRL: repositories

                    deactivate RepositorySingleton
                    STRCTRL -> PLAT: getStoreRepository();
                    activate PLAT

                        PLAT --> STRCTRL : storeRepository

                    deactivate PLAT
                    STRCTRL -> PLAT : getStateRepository();
                    activate PLAT

                        PLAT --> STRCTRL : stateRepository

                    deactivate PLAT
                    STRCTRL -> PLAT : getDistrictRepository();
                    activate PLAT

                        PLAT --> STRCTRL : districtRepository

                    deactivate PLAT
                    STRCTRL -> PLAT : getCityRepository();
                    activate PLAT

                        PLAT --> STRCTRL : cityRepository

                    deactivate PLAT
            deactivate STRCTRL

            UI --> ADM : requests address data (street address, doorNumber, floorNumber, zipCode, state, district, city )
            deactivate UI

            ADM -> UI : types requested data
            activate UI

            UI --> ADM : shows store address data and asks to confirm
            deactivate UI

            ADM -> UI : submits data
            activate UI

                    UI -> STRCTRL :createStoreAddress(streetAddress, doorNumber, floorNumber, zipCode, state, district, city)
                    activate STRCTRL

                    STRCTRL -> Address : Address(streetAddress, doorNumber, floorNumber, zipCode, state, district, city)
                    activate Address

                    Address --> STRCTRL : address object
                    deactivate Address

                    STRCTRL -> UI : address
                    deactivate STRCTRL

            UI --> ADM : requests store data (ID, designation, emailAddress, phoneNumber)
            deactivate UI

            ADM -> UI : types requested data(ID, designation, emailAddress, phoneNumber)
            activate UI

                                UI -> STRCTRL :createStore(ID, designation, emailAddress, phoneNumber)
                                activate STRCTRL

                                STRCTRL -> StoreRepository : createStore(ID, designation, emailAddress, phoneNumber)
                                activate StoreRepository

                                StoreRepository --> STRCTRL : store
                                deactivate StoreRepository

                                STRCTRL -> UI : store
                                deactivate STRCTRL


            UI --> ADM : shows store data and asks to confirm
            deactivate UI

            ADM -> UI : submits data
            activate UI

                UI -> STRCTRL : registerAddressAtStore(store, address)
                activate STRCTRL

                STRCTRL -> StoreRepository : setAddress(address)
                activate StoreRepository

                StoreRepository --> STRCTRL : boolean
                deactivate StoreRepository

                STRCTRL --> UI : boolean
                deactivate STRCTRL

                UI --> ADM : shows store data and asks to confirm
                deactivate UI

                ADM -> UI : submits data
                activate UI

                UI -> STRCTRL : registerStore(store)
                activate STRCTRL

                STRCTRL -> StoreRepository : registerStore(store)
                activate StoreRepository

                StoreRepository --> STRCTRL : boolean
                deactivate StoreRepository

                STRCTRL --> UI : boolean
                deactivate STRCTRL

                UI --> ADM : displays operation success
                deactivate UI

           deactivate UI

deactivate ADM

@enduml