@startuml
autonumber
actor "NetworkManager" as NM
participant ":ListEmployeesUI" as UI
participant ":ListEmployeesController" as CTRL

participant ":Repositories" as REPO
participant "repositories :Repositories" as repo

participant ":StoreRepository" as REPOSTORE
participant "store :Store" as Store
participant ":EmployeeRepository" as REPOEMPLO

activate NM

NM -> UI : asks to list all Employees working in every Agency
activate UI

    UI -> CTRL**: create
    UI -> CTRL: getAllStores()
    activate CTRL

        CTRL -> REPO: getInstance()
        activate REPO
            CTRL <-- REPO: repositories
        deactivate REPO

        CTRL -> repo: getStoreRepository()
        activate repo
            CTRL <-- repo: storeRepository
        deactivate repo

        CTRL -> REPOSTORE: getStoreList()
        activate REPOSTORE

            CTRL <-- REPOSTORE: storeList
        deactivate REPOSTORE

        UI <-- CTRL: storeList
        deactivate CTRL

        UI -> CTRL: sort(storeList)
        activate CTRL

            UI <-- CTRL: sortedStoreList
        deactivate CTRL

loop for each store in storeList
        UI -> CTRL: getAllEmployees(store)
        activate CTRL

            CTRL -> REPOEMPLO: getAgentsList(store)
            activate REPOEMPLO

                CTRL <-- REPOEMPLO: agentsList
            deactivate REPOEMPLO

            UI <- CTRL: agentsList
        deactivate CTRL


        UI -> CTRL: getsortedAgentList()
        activate CTRL


            UI <-- CTRL: sortedAgentList

        deactivate CTRL
            NM <-- UI: shows storeID and sorted list of agents by alphabetical
    deactivate UI

end




deactivate NM

@enduml