@startuml
'https://plantuml.com/sequence-diagram

@startuml

class ListEmployeesUI
class ListEmployeesController
{
+getEmployeesList()
}


class Repositories
{
-description
-StoreRepository storeRepository
+getInstance() : Repositories
+getStoreRepository()
}



class Store
{
-int ID
-String designation
-String phoneNumber
-String email
-List<Person> employees
-List<Advertisement> advertisements
+Store(int ID, String designation, String phoneNumber, String email, String street, City city, String postalCode)
+getEmployees()
+getAdvertisements()
}


class StoreRepository
{
-List<Store> storeList
+getStoreList()
+sortStoreListByNumberOfAdvertisements()
+getEmployeesOfStore(Store store)
}

class PersonRepository {
-List<Person> personList
+getPersonList()
+sortListAlphabetically()
}

class Person
{
- name
- phoneNumber
- email
- passportNumber
- taxNumber
+ Person(String name, String phoneNumber, String email, String passportNumber, String taxNumber)
+ getName()
}

class SortAlphabeticallyComparator
{

}

Repositories --> Repositories : instance
ListEmployeesController ..> Repositories
ListEmployeesUI ..> ListEmployeesController
Repositories "1" -- "1" StoreRepository : has >
Repositories "1" -- "1" PersonRepository : has >
StoreRepository "1" -- "*" Store : has >
PersonRepository ..> SortAlphabeticallyComparator
PersonRepository "1" -- "*" Person : has >
Store "1" .. "*" Person : has >

@enduml