@startuml
'https://plantuml.com/sequence-diagram

@startuml

class ListEmployeesUI
class ListEmployeesController
{
}


class Repositories
{
-description
-StoreRepository storeRepository
+getInstance() : Repositories
+getStoreRepository()
}



class Store
{
-int ID
-String designation
-String phoneNumber
-String email
-List<Person> employees
-List<Advertisement> advertisements
+Store(int ID, String designation, String phoneNumber, String email, String street, City city, String postalCode)
+getEmployees()
+getAdvertisements()
}


class StoreRepository
{
-List<Store> storeList
+getStoreList()
+sortStoreListByNumberOfAdvertisements()
+getEmployeesOfStore(Store store)
}

class EmployeeRepository {
-List<Employee> employeeList
+getEmployeeList()
+sortListAlphabetically()
}

class Employee
{
- name
- phoneNumber
- email
- passportNumber
- taxNumber
+ Employee (String name, String phoneNumber, String email, String passportNumber, String taxNumber)
+ getName()
}

class SortAlphabeticallyComparator
{

}

Repositories --> Repositories : instance
ListEmployeesController ..> Repositories
ListEmployeesUI ..> ListEmployeesController
Repositories "1" -- "1" StoreRepository : has >
Repositories "1" -- "1" EmployeeRepository : has >
StoreRepository "1" -- "*" Store : has >
EmployeeRepository ..> SortAlphabeticallyComparator
EmployeeRepository "1" -- "*" Employee : has >
Store "1" .. "*" Employee : has >

@enduml