@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

'class Platform {
' -description
'}

class User {
    name
    email
    password
}

class Application {

}

'class System {
'}

'class Properties {
   'type of business
   ' type of property
   'number of rooms
'}



'class Employee {
''    name
'    email
'    position
'    phone
'}


User - Application: requests to \nshow properties >
''System - User: asks for filters >
'Platform "1" -- "*" App : has registered >
'Platform "1" -- "*" System : defines >
'App "1" - "0..*" Employee : has >
''Application "1" - System: has >
'Task "*" -- "1" Employee: created by >
'Employee "1" -- "*" Task : creates >
'Employee "0..1" -- "1" User: acts as >
''Properties - System: are registered in >
@enduml