@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US018 - System Sequence Diagram (SSD)

autonumber

actor StoreManager
participant System

activate StoreManager

    StoreManager -> System: asks to analyse the deals (on houses and apartments)
    activate System

        StoreManager <-- System: requests the path of the information file
    deactivate System

    StoreManager -> System: inserts the path of the information file
    activate System

        StoreManager <-- System: show the regression models and request to select one (simple-linear or multi-linear)
    deactivate System

    StoreManager -> System: selects a regression model (simple-linear or multi-linear)
    activate System

        StoreManager <-- System: asks for the parameters to be used (eg. area, number of bathrooms, etc...)
    deactivate System

        StoreManager -> System: inserts the parameters to be used (eg. area, number of bathrooms, etc...)
        activate System

            StoreManager <-- System: displays prediction
@enduml