@startuml
left to right direction

actor "Unregistered user" as unUser #grey
actor "Agent" as Agent #grey
actor "System Administrator" as Admin #grey
actor "Owner" as Owner #grey

rectangle "RealEstate USA App"{
 usecase "US1 - Display Listed Properties" as UC1
 usecase "US7 - Register in the system" as UC7
 usecase "US2 - Publish the Announcements on the System" as UC2
 usecase "US4 - Submit a request" as UC4
 usecase "US5 - Register a store" as UC5
 usecase "US3 - Register the Employees" as UC3
 usecase "US6 - specify states, districts and cities in the system" as UC6
 }
 unUser -- UC1
 Agent -- UC2
 Admin -- UC5
 Admin -- UC6
 Admin -- UC3
 Owner -- UC4
 unUser -- UC7
@enduml