@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - USS005

autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a store
    activate System

        System --> Employee : requests data for store address
    deactivate System

    Employee -> System : types requested data (street address, doorNumber, floorNumber, zipCode, state, district, city )
    activate System

        System --> Employee : asks for store data
    deactivate System

    Employee -> System: types requested store data (ID, designation, emailAddress, phoneNumber)
    activate System

        System --> Employee : shows store preview and asks for confirmed submission
    deactivate System

    Employee -> System : confirms submission
    activate System

        System --> Employee : registers the store
    deactivate System

        System --> Employee : displays operation success
    deactivate System

@enduml