@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US015 - System Sequence Diagram (SSD)

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

Agent -> System : Intend to list all booking requests for properties managed by the agent.
activate System

"System" --> Agent: request a specific period (begin date).

deactivate System

Agent -> System : Select specific period (begin date).
activate System

"System" --> Agent: request a specific period (end date).

deactivate System

Agent -> System : Select specific period (end date).
activate System


"System" --> Agent : show a list for a specific period sorted in ascending gorder (begin date, end date).



@enduml