@startuml
'https://plantuml.com/sequence-diagram

@startuml

class ListRequestGUI {

}

class ListRequestController{
-Repositories repositories

+getAnnouncement()
+getInstance()
+checkMinutes()
+checkHour()
+checkYear()
+checkMonth()
+checkDay()
+checkIfValidVisit()
+addMessage()
}

class Repositories{
+Repositories()
+getAuthenticationRepository()
+getInstance()
+getMessageRepository()
+getAnnouncementsRepository()
}

class MessageRepository{
-List<Message> MessageList
-List<Message> MessageCompleteList

+getMessageList()
}

class AuthenticationRepository{
+getCurrentUserSession()
}

class AgentRepository{
-email
+getAgentByEmail()
}

class Agent{
email
}

ListRequestGUI --> ListRequestController

ListRequestController --> Repositories

ListRequestController --> MessageRepository
ListRequestController --> AuthenticationRepository
ListRequestController --> AgentRepository

Agent--> AgentRepository




@enduml