@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Agent" as AGENT
participant "ListRequestsGUI" as UI
participant "controller\n:ListRequestController" as CTRL
participant "requestRepository\n:RequestRepository" as REQREPO
participant ":sortingMethods\nSortingMethods.properties" as SM


title "US015 - Alternative flux (Sorting Methods)"

activate UI

UI -> CTRL : sortedList = getRequestsSorted(requestsAgent)
activate CTRL

CTRL -> REQREPO: getRequestsSorted(requestList)
activate REQREPO

REQREPO -> SM : System.getProperties()
activate SM

SM --> REQREPO : returns algorithm
deactivate

REQREPO --> CTRL : sortedList
deactivate

CTRL --> UI : sortedList
deactivate

@enduml