@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods


class SystemAdministrator{
}


class Employee {
    employeeName
    employeeEmail
    employeePhoneNumber
    employeeTaxNumber
    employeeAgency
    passportCardNumber
    employeeAddress
}


class Store{
storeName
storeLocation
storePhoneNumber
storeEmail
}

class Role{
}


SystemAdministrator "1"--"0...*" Employee: registe >
SystemAdministrator --|> Employee: is an


Employee "1"--"1" Store: works for >
Employee "0...*"--"1...*" Role: has >


@enduml