@startuml
autonumber

title US017 - Sequence Diagram (SSD)

actor "NetworkManager" as NM
participant ":ListDealsUI" as UI
participant ":ListDealsController" as Controller

participant ":Repositories" as PLAT
participant "repositories :\nRepositories" as REP
participant "dealRepository :\nDealRepository" as DR
participant "dealMapper" as DEALMAPPER
participant "dealDTO" as DEALDTO


activate NM

    NM -> UI : asks to display the list of all the deals made

    activate UI

    UI --> Controller** : create

    activate Controller

    Controller -> PLAT : getInstance()

    activate PLAT

    PLAT --> Controller : repositories

    deactivate PLAT

    Controller -> REP : getDealsRepository()

    activate REP

    REP --> Controller : dealsRepository

    deactivate REP

    UI -> Controller : getDealsList()

    Controller -> DR : getDeals()

    activate DR

    DR --> Controller : deals

    deactivate DR

    loop for each (deal : dealList)

    Controller -> DEALMAPPER : toDto(deal)

    activate DEALMAPPER

    DEALMAPPER -> DEALDTO : createDTO(deal)

    activate DEALDTO

    DEALDTO --> DEALMAPPER : dealDTO

    deactivate DEALDTO

    DEALMAPPER --> DEALMAPPER : addToDealStoList(dealDTO)
    activate DEALMAPPER

    end

    DEALMAPPER --> Controller : dealDTOList

    deactivate DEALMAPPER

    deactivate DEALMAPPER

    Controller --> UI : dealDTOList

    deactivate Controller

        UI --> NM : shows the two different sorting methods \nand asks to select one

    deactivate UI

    NM -> UI : selects the order of sorting (ascending or descending)

    activate UI

    UI --> NM : shows the list of all the deals made sorted \nby the selected sorting method and order

    deactivate UI

deactivate NM

@enduml