@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title US008 - Domain Model


class Agent {
    name
    citizenCardNumber
    tax number
    address
    email
    phoneNumber
    agency
}

class Property {
    area
    distanceFromCityCenter
    propertyType
}

class PhotographList {
}

class Photos {
    photoURI
    photoID
}

class Announcement {
    date
    comissionType
    comission
    requestType
    price
}

class Residence {
    numberBedrooms
    numberBathrooms
    numberParking
}

class AvailableEquipmentList {
}

class AvailableEquipment {
    availableEquipment
}

class House {
    basement
    inhabitableLoft
    sunExposure
}

class Address {
    streetAddress
    doorNumber
    floorNumber
    zipCode
    state
    district
    city
}

class Request

Agent "1" - "1" ListOfRequests : sees >
ListOfRequests "1" -- "*" Request : has >
Announcement "1" -- "1" Property : has >
Agent "1" -- "1" Request : chooses >
Property "1" -- "1" Residence : can be >
Property "1" - "1" Address : has >
Residence "1" -- "1" House : can be >
Request "1" -- "1" Property : has >
Agent "1" -- "1" Announcement : creates >
Residence "1" - "1" AvailableEquipmentList : has >
AvailableEquipmentList "1" - "*" AvailableEquipment : has >
Announcement "1" - "1" PhotographList : has >
PhotographList "1" - "1 - 30" Photos : has >


@enduml