@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods


class SystemAdministrator{
  name
  email
  citizenCardNumber
  taxNumber
  physycalAdress
  phoneNumber
}


class Employee {
    name
    citizenCardNumber
    adress
    email
    phoneNumber
    taxNumber
    branch of network
    agency
}

SystemAdministrator "1"--"0...*" Employee: registed by <
@enduml