@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Property{
-float price
-String typeOfProperty
+getPrice()
+getTypeOfProperty()
}

class Announcement{
-String city
-String state
+getCity()
+getState()
}


class ScheduleVisitUI{
}

class MessageRepository{
}

class UserRepository{
}

class ScheduleVisitController{
+DisplayPropertiesController(announcementsRepository)
+displayProperties(number of rooms, type of business, type of property)
+getAnnouncements()
+sortPropertiesCity()
+sortPropertiesPrice()
+sortPropertiesState()
}


class Repositories{
-Repositories()
+getInstance(): Repositories
+getAnnouncementsRepository()
}

class AnnouncementsRepository{
-ArrayList<Announcement> announcements
+getAnnouncementByCharacteristics(number of rooms, type of business, type of property)
+getAnnouncement()
+sortPropertiesCityAscending()
+sortPropertiesCityDescending()
+sortPropertiesPriceAscending()
+sortPropertiesPriceDescending()
+sortPropertiesStateAscending()
+sortPropertiesStateDescending()
}

class Message{
}

class User{
}


ScheduleVisitUI -> ScheduleVisitController

ScheduleVisitController --> Repositories

Repositories --> AnnouncementsRepository
Repositories --> UserRepository
Repositories --> MessageRepository

MessageRepository <- Message

UserRepository <- User

AnnouncementsRepository <- Announcement

Property --> Announcement
@enduml