@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Agent" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Asks to see the list of all booking requests

    activate System

    System --> Employee : Shows the list off all booking requests and asks to select one

    deactivate System

    Employee -> System : Selects a booking request and asks to select the option to respond\n to the user that scheduled the visit.

    activate System

     Employee -> System : Selects a booking request and asks to select the option to respond\n to the user that scheduled the visit.

     activate System

    Employee -> System : Selects the option to respond to the user that scheduled the visit.

    activate System

    System --> System : Sends the response message by email to the user that scheduled the visit

    System --> Employee : displays operation success

    deactivate System

@enduml