@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US001 - System Sequence Diagram (SSD)

autonumber

actor "Unregistered User" as Customer
participant ":System" as System

activate Customer

    Customer -> System : asks to display properties
    activate System

        System --> Customer : requests specific (type of property) data
    deactivate System
opt data is given
    Customer -> System : types requested data (type of business (renting or buying), \ntype of property, number of rooms)
    activate System

        System --> Customer : shows list of properties that correspond to the data
    deactivate System
end

opt no data is given
    Customer -> System : decides not to type the required data
        activate System

            System --> Customer : allows the client to sort through all properties that are on \nsale or renting
        deactivate System
end

@enduml